# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160825_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='static/music'),
        ),
    ]
