# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20161211_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to='static/music'),
        ),
    ]
